version: '3.9'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console Web
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  pyspark:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pyspark
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin123
      AWS_REGION: us-east-1
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - minio
      - nessie
    command: /bin/bash -c "python3 app/main.py; while sleep 1; do :; done"
  nessie:
   image: projectnessie/nessie:latest
   container_name: nessie
   ports:
     - "19120:19120"
  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio
    # Portas para acesso externo (UI e JDBC/ODBC)
    ports:
      - "9047:9047" # Web UI (Acessar: http://localhost:9047)
      - "32010:32010"
    environment:
      # Definindo a memória Heap, ajuste conforme a RAM disponível na sua máquina
      DREMIO_MAX_HEAP_MEMORY_SIZE_MB: 4096 
    volumes:
      # Volumes para persistir dados e configurações do Dremio
      - dremio_data:/opt/dremio/data
      - dremio_conf:/opt/dremio/conf
      - ./dremio_config/log4j2.xml:/opt/dremio/conf/log4j2.xml
    depends_on:
      # Dremio precisa do Nessie (Catálogo) e do MinIO (Armazenamento)
      - nessie
      - minio  
      
volumes:
  minio_data:
  dremio_data:
  dremio_conf:
