version: '3.9'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console Web
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  pyspark:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pyspark
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin123
      AWS_REGION: us-east-1
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - minio
    command: ["/bin/bash", "-c", "while sleep 1; do :; done"]
  
volumes:
  minio_data: